# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('emailid', models.CharField(max_length=100)),
            ],
        ),
    ]
